<script setup>
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessageBox } from 'element-plus';
import { api } from '../api/index.js';
import { usePolling } from '../components/polling.js';
import StatusTag from '../components/StatusTag.vue';
const jobs = ref([]), total = ref(0), page = ref(1), error = ref(''), libraries = ref([]), dialog = ref(false), libraryId = ref(''), dryRun = ref(true), busy = ref(false), router = useRouter();
async function load() { try { const r = await api(`/workflows?page=${page.value}&pageSize=20`, { quiet: true }); jobs.value = r.items; total.value = r.total; error.value = ''; } catch (e) { error.value = e.message; } }
usePolling(load);
onMounted(async () => { try { libraries.value = (await api('/dashboard')).libraries; } catch {} });
async function scan() { busy.value = true; try { if (!dryRun.value) await ElMessageBox.confirm('扫描后将自动应用唯一可靠候选，有歧义的条目会等待人工确认。继续？', '启动识别', { confirmButtonText: '扫描并识别', cancelButtonText: '取消' }); const job = await api('/workflows/scan', { method: 'POST', body: { dryRun: dryRun.value, ...(libraryId.value ? { libraryId: libraryId.value } : {}) } }); await router.push(`/jobs/${job.id}`); } catch {} finally { busy.value = false; } }
</script>
<template><el-alert title="任务记录保存在当前服务进程内，服务重启后会清空。" type="info" show-icon :closable="false" class="notice" /><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="notice" /><section class="panel"><div class="panel-header"><h2>全部任务 <span class="muted">{{ total }} 条</span></h2><div class="toolbar"><el-button @click="load">刷新</el-button><el-button type="primary" @click="dialog = true">新建扫描任务</el-button></div></div><div class="table-wrap"><el-table :data="jobs"><el-table-column label="任务" min-width="210"><template #default="{ row }"><router-link :to="`/jobs/${row.id}`">{{ row.input.hash ? `下载通知 · ${row.input.hash.slice(0, 12)}` : row.input.dryRun ? '候选预览' : '媒体扫描识别' }}</router-link></template></el-table-column><el-table-column prop="stage" label="当前阶段" min-width="190" show-overflow-tooltip /><el-table-column label="状态" width="115"><template #default="{ row }"><StatusTag :status="row.status" /></template></el-table-column><el-table-column prop="itemCount" label="媒体数" width="85" /><el-table-column label="创建时间" min-width="170"><template #default="{ row }">{{ new Date(row.createdAt).toLocaleString('zh-CN') }}</template></el-table-column><el-table-column label="操作" width="90"><template #default="{ row }"><el-button text type="primary" @click="router.push(`/jobs/${row.id}`)">详情 →</el-button></template></el-table-column></el-table></div><div class="pagination"><span class="muted">页面可见时每 3 秒更新</span><el-pagination v-model:current-page="page" :total="total" :page-size="20" layout="prev, pager, next" @current-change="load" /></div></section><el-dialog v-model="dialog" title="创建媒体扫描任务" width="min(480px, 94vw)"><el-form label-position="top"><el-form-item label="目标媒体库"><el-select v-model="libraryId" style="width:100%"><el-option label="全部电影 / 电视剧库" value="" /><el-option v-for="l in libraries" :key="l.ItemId" :value="l.ItemId" :label="l.Name" /></el-select></el-form-item><el-form-item label="运行方式"><el-radio-group v-model="dryRun"><el-radio :value="true">预览候选</el-radio><el-radio :value="false">识别并应用</el-radio></el-radio-group></el-form-item><p class="muted">将等待媒体库扫描结束，再处理未识别条目。预览会调用 DeepSeek 提取名称，但不写入媒体元数据。</p></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="busy" @click="scan">开始扫描</el-button></template></el-dialog></template>
