<script setup>
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessageBox } from 'element-plus';
import { api } from '../api/index.js';
const items = ref([]), total = ref(0), page = ref(1), libraries = ref([]), libraryId = ref(''), selected = ref([]), loading = ref(false), busy = ref(false), error = ref(''), router = useRouter();
async function load() { loading.value = true; try {
  libraries.value = (await api('/dashboard', { quiet: true })).libraries;
  if (libraryId.value && !libraries.value.some(l => l.ItemId === libraryId.value)) { libraryId.value = ''; page.value = 1; }
  const query = new URLSearchParams({ page: page.value, pageSize: 20 }); if (libraryId.value) query.set('libraryId', libraryId.value);
  const r = await api(`/media/unidentified?${query}`, { quiet: true }); items.value = r.items; total.value = r.total; selected.value = []; error.value = '';
} catch (e) { items.value = []; total.value = 0; selected.value = []; error.value = e.message; } finally { loading.value = false; } }
onMounted(load);
async function start(dryRun) { busy.value = true; try { if (!dryRun) await ElMessageBox.confirm(`将处理${selected.value.length ? `选中的 ${selected.value.length} 项媒体` : '当前库范围内所有未识别媒体'}，自动应用规则匹配或 AI 明确选出的候选。继续？`, '启动媒体识别', { confirmButtonText: '识别并应用', cancelButtonText: '取消' }); const job = await api('/workflows/scan', { method: 'POST', body: { dryRun, ...(libraryId.value ? { libraryId: libraryId.value } : {}), ...(selected.value.length ? { itemIds: selected.value.map(i => i.Id) } : {}) } }); await router.push(`/jobs/${job.id}`); } catch {} finally { busy.value = false; } }
</script>
<template><el-alert title="电视剧按文件夹名称识别，电影按文件名称识别。首次处理全部媒体（含 Jellyfin 已识别条目），以后按添加日期游标处理新增及未完成条目。" type="info" show-icon :closable="false" class="notice" /><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="notice" /><section class="panel"><div class="panel-header"><h2>未识别媒体 <span class="muted">{{ total }} 项</span></h2><div class="toolbar"><el-select aria-label="目标媒体库" placeholder="全部目标库" v-model="libraryId" style="width:170px" @change="page = 1; load()"><el-option label="全部目标库" value="" /><el-option v-for="l in libraries" :key="l.ItemId" :label="l.Name" :value="l.ItemId" /></el-select><el-button :loading="loading" @click="load">刷新列表</el-button></div></div><div class="panel-body toolbar" style="padding-top:16px;padding-bottom:16px"><span class="muted" style="margin-right:auto">{{ selected.length ? `已选择 ${selected.length} 项` : '未选择条目时，处理当前目标库内全部未识别媒体' }}</span><el-button :loading="busy" :disabled="!total" @click="start(true)">预览候选</el-button><el-button type="primary" :loading="busy" :disabled="!total" @click="start(false)">识别并应用</el-button></div><div class="table-wrap" v-loading="loading"><el-table :data="items" row-key="Id" @selection-change="rows => selected = rows"><el-table-column type="selection" width="45" /><el-table-column prop="Name" label="媒体名称" min-width="200" /><el-table-column label="类型" width="85"><template #default="{ row }">{{ row.Type === 'Series' ? '电视剧' : '电影' }}</template></el-table-column><el-table-column prop="ProductionYear" label="年份" width="85" /><el-table-column label="文件路径" min-width="300" show-overflow-tooltip><template #default="{ row }"><span class="path">{{ row.Path }}</span></template></el-table-column><template #empty><div class="empty-hint">当前没有未识别媒体。新下载入库后可再次检查。</div></template></el-table></div><div class="pagination"><span class="muted">自动发现当前全部剧集和电影库</span><el-pagination v-model:current-page="page" :total="total" :page-size="20" layout="prev, pager, next" @current-change="load" /></div></section></template>
