<script setup>
import { ref, onMounted } from 'vue';
import { ElMessage } from 'element-plus';
import { api } from '../api/index.js';
const data = ref(null), checks = ref({}), error = ref(''), checking = ref(false);
const names = { qbittorrent: 'qBittorrent', jellyfin: 'Jellyfin', deepseek: 'DeepSeek' };
async function load() { try { data.value = await api('/dashboard', { quiet: true }); error.value = ''; } catch (e) { error.value = e.message; } }
onMounted(load);
async function check() { checking.value = true; try { checks.value = await api('/connections/check', { method: 'POST' }); } catch {} finally { checking.value = false; } }
async function copy(text) { try { await navigator.clipboard.writeText(text); ElMessage.success('已复制'); } catch { ElMessage.info('当前浏览器不支持复制，请手动复制。'); } }
</script>
<template><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="notice" /><div class="settings-grid"><section class="panel"><div class="panel-header"><h2>服务连接</h2><el-button :loading="checking" @click="check">检查连接</el-button></div><div class="panel-body"><div v-for="(c, key) in data?.connections" :key="key" class="config-row"><label>{{ names[key] }}</label><div style="display:flex;gap:15px;align-items:center;flex-wrap:wrap"><strong class="safe-link">{{ c.url }}</strong><el-tag :type="checks[key]?.ok === false ? 'danger' : checks[key]?.ok ? 'success' : 'info'">{{ checks[key]?.ok === false ? '连接失败' : checks[key]?.ok ? '连接正常' : '未检查' }}</el-tag></div><p class="muted">API 密钥：{{ c.configured ? '已配置 · 不在面板显示' : '未配置' }}<span v-if="c.model">　模型：{{ c.model }}</span></p><p v-if="checks[key]?.error" class="error">{{ checks[key].error }}</p><p v-if="checks[key]?.ok" class="muted">{{ typeof checks[key].result === 'string' ? checks[key].result : checks[key].result.version || checks[key].result.models?.join(' / ') }}</p></div><div class="config-row"><label>下载路径映射</label><strong class="path">{{ data?.pathMapping?.from || '原路径' }} → {{ data?.pathMapping?.to || '原路径（不转换）' }}</strong></div><p class="muted">连接凭据、模型和路径映射在服务的 .env 文件中维护，修改后重启服务生效。DeepSeek 连通检查仅查询可用模型。</p></div></section><section class="panel"><div class="panel-header"><h2>下载完成通知</h2><span class="muted">qBittorrent → Media Flow</span></div><div class="panel-body"><div class="config-row"><label>回调地址</label><strong class="safe-link">{{ data?.callbackUrl }}</strong><div style="margin-top:12px"><el-button size="small" @click="copy(data.callbackUrl)">复制地址</el-button></div></div><p class="muted" style="line-height:1.9">在 qBittorrent 的下载设置中启用“下载完成后运行外部程序”，使用项目附带的通知脚本。脚本需部署在 qBittorrent 所在服务器，并配置可访问的回调地址。</p><label class="muted">Windows 命令模板</label><pre class="code">node "E:\personal\z-media-workflow\scripts\notify-completed.mjs" "%I"</pre><label class="muted">Linux / Docker 命令模板</label><pre class="code">node /opt/z-media-workflow/scripts/notify-completed.mjs "%I"</pre><el-alert title="通知脚本使用独立 WORKFLOW_API_TOKEN；管理令牌不能用于下载回调。" type="info" :closable="false" show-icon /><p class="muted" style="line-height:1.9">确保 RSS 规则将电视剧保存到剧集库目录，电影保存到电影库目录。本服务不会移动下载文件。</p></div></section></div><section v-if="data" class="panel"><div class="panel-header"><h2>目标库挂载</h2><el-button size="small" @click="load">刷新</el-button></div><div class="table-wrap"><el-table :data="data.libraries"><el-table-column prop="Name" label="媒体库" width="140" /><el-table-column label="类型" width="100"><template #default="{ row }">{{ row.CollectionType === 'movies' ? '电影' : '电视剧' }}</template></el-table-column><el-table-column label="目录" min-width="240"><template #default="{ row }"><span class="path">{{ row.Locations?.join(', ') }}</span></template></el-table-column><el-table-column prop="ItemId" label="库 ID" min-width="280" /></el-table></div></section></template>
