<script setup>
import AddedNotification from '../components/AddedNotification.vue';
import TorrentCleanup from '../components/TorrentCleanup.vue';
import { ref, onMounted } from 'vue';
import { ElMessage } from 'element-plus';
import { api } from '../api/index.js';
import CompletionNotification from '../components/CompletionNotification.vue';
const data = ref(null), checks = ref({}), error = ref(''), checking = ref(false);
const names = { qbittorrent: 'qBittorrent', jellyfin: 'Jellyfin', deepseek: 'DeepSeek' };
async function load() { try { data.value = await api('/dashboard', { quiet: true }); error.value = ''; } catch (e) { error.value = e.message; } }
onMounted(load);
async function check() { checking.value = true; try { checks.value = await api('/connections/check', { method: 'POST' }); } catch {} finally { checking.value = false; } }
async function copy(text) { try { await navigator.clipboard.writeText(text); ElMessage.success('已复制'); } catch { ElMessage.info('当前浏览器不支持复制，请手动复制。'); } }
</script>
<template><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="notice" /><div class="settings-grid"><section class="panel"><div class="panel-header"><h2>服务连接</h2><el-button :loading="checking" @click="check">检查连接</el-button></div><div class="panel-body"><div v-for="(c, key) in data?.connections" :key="key" class="config-row"><label>{{ names[key] }}</label><div style="display:flex;gap:15px;align-items:center;flex-wrap:wrap"><strong class="safe-link">{{ c.url }}</strong><el-tag :type="checks[key]?.ok === false ? 'danger' : checks[key]?.ok ? 'success' : 'info'">{{ checks[key]?.ok === false ? '连接失败' : checks[key]?.ok ? '连接正常' : '未检查' }}</el-tag></div><p class="muted">API 密钥：{{ c.configured ? '已配置 · 不在面板显示' : '未配置' }}<span v-if="c.model">　模型：{{ c.model }}</span></p><p v-if="checks[key]?.error" class="error">{{ checks[key].error }}</p><p v-if="checks[key]?.ok" class="muted">{{ typeof checks[key].result === 'string' ? checks[key].result : checks[key].result.version || checks[key].result.models?.join(' / ') }}</p></div><div class="config-row"><label>下载路径映射</label><strong class="path">{{ data?.pathMapping?.from || '原路径' }} → {{ data?.pathMapping?.to || '原路径（不转换）' }}</strong></div><p class="muted">连接凭据、模型和路径映射在服务的 .env 文件中维护，修改后重启服务生效。DeepSeek 连通检查仅查询可用模型。</p></div></section><CompletionNotification v-if="data" :callback-url="data.callbackUrl" :auth-required="data.webhookAuthRequired" /></div><AddedNotification v-if="data" :callback-url="data.addedCallbackUrl" :auth-required="data.webhookAuthRequired" /><TorrentCleanup v-if="data" /><section v-if="data" class="panel"><div class="panel-header"><h2>目标库挂载</h2><el-button size="small" @click="load">刷新</el-button></div><div class="table-wrap"><el-table :data="data.libraries"><el-table-column prop="Name" label="媒体库" width="140" /><el-table-column label="类型" width="100"><template #default="{ row }">{{ row.CollectionType === 'movies' ? '电影' : '电视剧' }}</template></el-table-column><el-table-column label="目录" min-width="240"><template #default="{ row }"><span class="path">{{ row.Locations?.join(', ') }}</span></template></el-table-column><el-table-column prop="ItemId" label="库 ID" min-width="280" /></el-table></div></section></template>
